---
title: Docente
engine: knitr
# listing:
#   contents: encuentros/*/index.qmd
#   fields: [image, title, author, subtitle]
#   type: grid
#   sort:
#     - filename
---

**PABLO TISCORNIA**

Soci칩logo y Cient칤fico de Datos. Especializado en metodolog칤a, producci칩n, procesamiento y comunicaci칩n de informaci칩n estad칤stica. Trabaj칠 como analista y procesador de datos en las oficinas estad칤sticas de la Ciudad de Buenos Aires ([DGEyC](https://www.estadisticaciudad.gob.ar/eyc/)) y Argentina ([INDEC](https://www.indec.gob.ar/)), y como Coordinador de Datos en la Direcci칩n Nacional de Mercados y Estad칤stica ([DNMYE](https://www.yvera.tur.ar/sinta/)), del Ministerio de Turismo y Deportes de la Naci칩n. Actualmente estoy trabajando como Cient칤fico de datos para [C40 Cities](https://www.c40.org/).

## Docencia y R:

-   Instructor Certificado de [The Carpentries](https://carpentries.org/)

Van ya m치s de `r lubridate::year(lubridate::today()) - 2019` a침os dise침ando y llevando adelante cursos de R, algunos de ellos son:

-   [Ciencias Sociales Computacionales y Humanidades Digitales (IDAES-UNSAM)](https://noticias.unsam.edu.ar/wp-content/uploads/2022/02/Cs-Computacionales-dga2022.pdf). M칩dulo 1. Introducci칩n a la Ciencia de Datos para Cient칤ficos Sociales

-   [Big Data e Inteligencia Territorial (FLACSO) - M칩dulo Ciencia de Datos I](https://www.flacso.org.ar/formacion-academica/big-data-e-inteligencia-territorial/)

-   [Instrumentos de An치lisis Urbanos II (UTDT)](https://tuqmano.github.io/geo_utdt/index.html)

-   [Introducci칩n a R para Ciencias Sociales - IIGG](https://pablotis.github.io/r_iigg/)

-   [Software estad칤stico R, aplicado al an치lisis y procesamiento de la informaci칩n estad칤stica del INDEC.](https://github.com/pablotis/Curso_R_INDEC)

## Mundo R:

He participado en la organizaci칩n y difusi칩n de la comunidad de [R en Buenos Aires](https://renbaires.github.io/), en el desarrollo de los paquetes [eph](https://holatam.github.io/eph/), [herramientas](https://dnme-minturdep.r-universe.dev/herramientas), [comunicacion](https://dnme-minturdep.r-universe.dev/comunicacion) y [evyth](https://dnme-minturdep.r-universe.dev/evyth).

游닇 Pod칠s encontrar parte de mi recorrido y trabajo con R en mi blog [estaci칩n-R](https://estacion-r.netlify.app/), buscar Tips sobre R con [rtips (twitter)](https://twitter.com/r_tipss)/[rtips (Mastodon)](@r_tips@botsin.space) y descubrir [Asombrosos paquetes de R en Latinoam칠rica](https://github.com/pablotis/asombrosos-paquetes-r-latinoamerica), proyectos que llevo adelante como aporte a la comunidad.

Podemos cruzarnos en: [洧뎶 estacion-r](https://twitter.com/r_tips) \| [Mastodon 游붞](https://mastodon.social/deck/@r_tips@botsin.space) \| [Github](https://github.com/pablotis) \| [游 estacion-r](https://estacion-r.netlify.app/) \| [洧뎶 pabblo_h](https://twitter.com/pabblo_h)

------------------------------------------------------------------------
